// Generated by FlutterFire CLI for rit-hostel-app-b1a1c.
// Run `flutterfire configure` to regenerate.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static bool get isConfigured => true;

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform. '
          'Run `flutterfire configure` to add iOS/macOS.',
        );
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVhup1hZKnLq6eWyNiTpSn796Z80CJnDA',
    appId: '1:28247779916:web:7da3a5d652c1ac5129a2e9',
    messagingSenderId: '28247779916',
    projectId: 'rit-hostel-app-b1a1c',
    authDomain: 'rit-hostel-app-b1a1c.firebaseapp.com',
    storageBucket: 'rit-hostel-app-b1a1c.firebasestorage.app',
    measurementId: 'G-HVT3LZ65Z0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKbRvfuwPK-ZgyVCAvMJsPvTAq74ymTns',
    appId: '1:28247779916:android:8d44b433a874611129a2e9',
    messagingSenderId: '28247779916',
    projectId: 'rit-hostel-app-b1a1c',
    storageBucket: 'rit-hostel-app-b1a1c.firebasestorage.app',
  );
}
